name: Combot Main CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project with cache
        run: ./gradlew build --stacktrace

      - name: Run app unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Run combot unit tests
        run: ./gradlew :combot:testDebugUnitTest

      - name: Get version from Gradle
        id: get_version
        run: |
          VERSION=$(./gradlew :combot:properties -q | grep '^version:' | awk '{print $2}')
          if [[ "$VERSION" == "unspecified" ]]; then
            echo "ERROR: Version not set in Gradle!"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Publish combot to GitHub Packages
        if: github.ref == 'refs/heads/main'
        run: ./gradlew :combot:publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git tag automatically
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
            
          if git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists. Skipping."
          else
            echo "Creating tag ${{ env.VERSION }}..."
            git tag -a "${{ env.VERSION }}" -m "Release ${{ env.VERSION }}"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git "${{ env.VERSION }}"
          fi

